language: android
jdk: oraclejdk7
sudo: false # Explicitly use container-based infrastructure http://docs.travis-ci.com/user/workers/container-based-infrastructure/
env:
  matrix:
    - ANDROID_TARGET=android-21
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used
    - build-tools-21.1.2

    # The SDK version used to compile the project
    - android-21

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

# Disable travis email notifications until builds work properly
notifications:
  email: true

before_script:
  - chmod +x gradlew
#  - chmod +x travis-acceptance-tests.sh

script: 
  - ./gradlew testProdDebugUnitTestCoverage
  - ./gradlew copyUnitTestBuildArtifacts
#  - ./travis-acceptance-tests.sh

after_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - ~/bin/artifacts upload artifacts

branches:
  only:
    - master

# Enable caching to speed up the build
cache:
  directories:
    - $HOME/.gradle
